#### BANK CUSTOMER DATASET REGRESSION USING LINEAR,LASSO,RIDGE

In [12]:
import pandas as pd
import numpy as np

In [13]:
data=pd.read_csv("bank_customers.csv")
data.head()
data.shape

(500, 4)

In [55]:
data

Customer ID        Age      Savings  Retire
0              0  39.180417  322349.8740       0
1              1  56.101686  768671.5740       1
2              2  57.023043  821505.4718       1
3              3  43.711358  494187.4850       0
4              4  54.728823  691435.7723       1
..           ...        ...          ...     ...
495          495  46.678128  704243.0776       1
496          496  43.545007  483175.9998       0
497          497  46.476724  354919.1987       0
498          498  50.903631  639789.9219       1
499          499  38.590586  491310.0096       0

[500 rows x 4 columns]

In [14]:
x=data.drop("Savings",axis=1)
y=data["Savings"]

In [15]:
from sklearn.model_selection import train_test_split
x_train ,x_test, y_train , y_test = train_test_split(x,y,test_size=1/3,random_state=0)


In [16]:
from sklearn.linear_model import LinearRegression
p = LinearRegression()
p.fit(x_train,y_train)

LinearRegression()

In [17]:
yp=p.predict(x_test)
yp

array([662996.06195132, 383946.91056325, 393298.89607588, 396426.04136075,
       678537.48102219, 663881.26709849, 667084.86708318, 407493.74111123,
       670639.71651651, 660280.97510975, 391197.69959978, 674455.47926438,
       678503.26283229, 401048.53370238, 667244.33789828, 674603.24385544,
       399773.90597099, 394586.74955695, 663378.97037057, 671051.2814942 ,
       673763.62587154, 689842.96288713, 672487.89538162, 653663.67510446,
       659040.25441216, 681064.04825946, 389256.17873329, 669184.97234986,
       374386.49292708, 382923.53600639, 407096.96856922, 655424.10715625,
       670053.19513227, 660281.40025557, 685022.17844261, 395527.54873731,
       669459.80570224, 677389.46911504, 397704.79912007, 667995.33448262,
       377012.63845172, 653050.81824724, 393248.4358448 , 386673.2964113 ,
       380436.06178767, 663071.62513388, 670796.7707809 , 393056.50279836,
       395845.28789524, 665185.66241126, 393545.05274958, 386301.73936206,
       670518.26426706, 3

In [18]:
p.score(x_test,y_test)

0.6363018374093089

In [19]:
p.score(x_train,y_train)

0.5814938431033596

In [20]:
from sklearn.metrics import mean_squared_error, r2_score
rmse = np.sqrt(mean_squared_error(y_test,yp))
rmse

117763.94522310069

In [23]:
from sklearn.linear_model import Lasso


In [21]:
x1 = data.drop("Savings",axis=1)
y1=data["Savings"]

In [24]:
k=Lasso()

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size = 1/3, random_state = 0)

In [26]:
k.fit(x_train,y_train)


Lasso()

In [27]:
k.score(x_train,y_train)

0.5814938428622023

In [28]:
k.score(x_test,y_test)

0.6362993410340858

In [29]:
from sklearn.linear_model import Ridge

In [30]:
x2 = data.drop("Savings",axis=1)
y2=data["Savings"]

In [31]:
z=Ridge()

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x2, y2, test_size = 1/3, random_state = 0)

In [33]:
z.fit(x_train,y_train)

Ridge()

In [34]:
z.score(x_train,y_train)

0.5813329912238552

In [35]:
z.score(x_test,y_test)

0.6341732622543282

## SOLVING USING KNN CLASSIFICATON

In [36]:
x=data.iloc[:,0:4]
y=data.iloc[:,3:4]

In [37]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier(n_neighbors=5)
k.fit(x,y)

<ipython-input-37-b2264f8eb4e7>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  k.fit(x,y)


KNeighborsClassifier()

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=1/3, random_state=0)

In [39]:
k.score(x_train,y_train) 

0.9009009009009009

In [40]:
k.score(x_test,y_test)

0.9341317365269461

In [41]:
data.isnull().any

<bound method DataFrame.any of      Customer ID    Age  Savings  Retire
0          False  False    False   False
1          False  False    False   False
2          False  False    False   False
3          False  False    False   False
4          False  False    False   False
..           ...    ...      ...     ...
495        False  False    False   False
496        False  False    False   False
497        False  False    False   False
498        False  False    False   False
499        False  False    False   False

[500 rows x 4 columns]>

In [8]:
print(data.isnull().sum())    # CHECKING FOR NULL VALUES 

Customer ID    0
Age            0
Savings        0
Retire         0
dtype: int64


Since only 2 features are present we are not looking for feature selection, feature redution also

In [42]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [43]:
print(x_test)

[[-1.11911760e+00  8.24137283e-01  5.69794830e-01  1.03359711e+00]
 [ 2.91632901e-02 -1.53207194e+00 -5.34443880e-01 -9.67494967e-01]
 [ 2.32212960e-01 -5.37957180e-01 -4.11405687e-03 -9.67494967e-01]
 [ 1.36649043e+00 -9.45915474e-01 -7.48796511e-01 -9.67494967e-01]
 [ 1.47851783e+00  9.06962063e-01  1.29275473e+00  1.03359711e+00]
 [-1.64424606e+00  1.29616761e+00  3.62873113e-02  1.03359711e+00]
 [ 4.63269482e-01  2.21783431e-01  6.39102862e-02  1.03359711e+00]
 [ 1.67456579e+00  1.83524787e-01 -8.57504616e-01 -9.67494967e-01]
 [-6.35999423e-01  1.41645720e+00  1.33772038e+00  1.03359711e+00]
 [-6.78009700e-01  1.88340910e-01  1.09148786e+00  1.03359711e+00]
 [-6.18589759e-02 -5.88818107e-01 -1.87397043e+00 -9.67494967e-01]
 [ 1.15643905e-03  1.43722381e+00 -2.13724106e-01  1.03359711e+00]
 [ 9.81396227e-01  1.24795340e+00  6.92740661e-01  1.03359711e+00]
 [ 2.74223237e-01  3.73481357e-01  1.81165900e-01 -9.67494967e-01]
 [-5.51978870e-01  9.46011719e-01  1.33317199e+00  1.03359711e